### ISSUE TITLE
elastix.GetTransformParameters() fails: AttributeError: type object 'object' has no attribute '__getattr__'

### ISSUE THREAD

**Issue by t-sanders** [kaspermarstal/SimpleElastix#20]
Installed on Ubuntu 14.04 64-bit using SuperBuild, I get the above error in the HelloWorld program on the "Introduction" page. 

Traceback (most recent call last):
  File "/usr/local/src/eclipse_workspace/Processor360/elastix/helloworld3.py", line 17, in <module>
    transformParameterMap = elastix.GetTransformParameters()
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 8776, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SimpleElastix, name)
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 76, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 71, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__' 

Hope you can help. (BTW: I just love SimpleElastics! Great job!)

**Comment by kaspermarstal** [comment]
Thanks, I hope you will find it useful!

And thanks for pointing out the error in the documentation. You get this error because there is no method `GetTransformParameters()`. It's called `GetTransformParameterMap()`. The docs have been updated accordingly.

**Comment by t-sanders** [comment]
Thanks!
